// ASYNC

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// ITEMS

export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const DELETE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';

// FILTERS

export const FILTER_ITEMS = 'FILTER_ITEMS';

// AUTH

export const AUTH_OPEN = 'AUTH_OPEN'
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SIGNUP_START = 'SIGNUP_START'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'


export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

// STATES
export const AUTH_ANONYMOUS = 'AUTH_ANONYMOUS'
export const AUTH_AWAITING_RESPONSE = 'AUTH_AWAITING_RESPONSE'
export const AUTH_LOGGED_IN = 'AUTH_LOGGED_IN'
